require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NewsletterSignUpsController do

  # This should return the minimal set of attributes required to create a valid
  # NewsletterSignUp. As you add validations to NewsletterSignUp, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all newsletter_sign_ups as @newsletter_sign_ups" do
      newsletter_sign_up = NewsletterSignUp.create! valid_attributes
      get :index
      assigns(:newsletter_sign_ups).should eq([newsletter_sign_up])
    end
  end

  describe "GET show" do
    it "assigns the requested newsletter_sign_up as @newsletter_sign_up" do
      newsletter_sign_up = NewsletterSignUp.create! valid_attributes
      get :show, :id => newsletter_sign_up.id.to_s
      assigns(:newsletter_sign_up).should eq(newsletter_sign_up)
    end
  end

  describe "GET new" do
    it "assigns a new newsletter_sign_up as @newsletter_sign_up" do
      get :new
      assigns(:newsletter_sign_up).should be_a_new(NewsletterSignUp)
    end
  end

  describe "GET edit" do
    it "assigns the requested newsletter_sign_up as @newsletter_sign_up" do
      newsletter_sign_up = NewsletterSignUp.create! valid_attributes
      get :edit, :id => newsletter_sign_up.id.to_s
      assigns(:newsletter_sign_up).should eq(newsletter_sign_up)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NewsletterSignUp" do
        expect {
          post :create, :newsletter_sign_up => valid_attributes
        }.to change(NewsletterSignUp, :count).by(1)
      end

      it "assigns a newly created newsletter_sign_up as @newsletter_sign_up" do
        post :create, :newsletter_sign_up => valid_attributes
        assigns(:newsletter_sign_up).should be_a(NewsletterSignUp)
        assigns(:newsletter_sign_up).should be_persisted
      end

      it "redirects to the created newsletter_sign_up" do
        post :create, :newsletter_sign_up => valid_attributes
        response.should redirect_to(NewsletterSignUp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved newsletter_sign_up as @newsletter_sign_up" do
        # Trigger the behavior that occurs when invalid params are submitted
        NewsletterSignUp.any_instance.stub(:save).and_return(false)
        post :create, :newsletter_sign_up => {}
        assigns(:newsletter_sign_up).should be_a_new(NewsletterSignUp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NewsletterSignUp.any_instance.stub(:save).and_return(false)
        post :create, :newsletter_sign_up => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested newsletter_sign_up" do
        newsletter_sign_up = NewsletterSignUp.create! valid_attributes
        # Assuming there are no other newsletter_sign_ups in the database, this
        # specifies that the NewsletterSignUp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NewsletterSignUp.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => newsletter_sign_up.id, :newsletter_sign_up => {'these' => 'params'}
      end

      it "assigns the requested newsletter_sign_up as @newsletter_sign_up" do
        newsletter_sign_up = NewsletterSignUp.create! valid_attributes
        put :update, :id => newsletter_sign_up.id, :newsletter_sign_up => valid_attributes
        assigns(:newsletter_sign_up).should eq(newsletter_sign_up)
      end

      it "redirects to the newsletter_sign_up" do
        newsletter_sign_up = NewsletterSignUp.create! valid_attributes
        put :update, :id => newsletter_sign_up.id, :newsletter_sign_up => valid_attributes
        response.should redirect_to(newsletter_sign_up)
      end
    end

    describe "with invalid params" do
      it "assigns the newsletter_sign_up as @newsletter_sign_up" do
        newsletter_sign_up = NewsletterSignUp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NewsletterSignUp.any_instance.stub(:save).and_return(false)
        put :update, :id => newsletter_sign_up.id.to_s, :newsletter_sign_up => {}
        assigns(:newsletter_sign_up).should eq(newsletter_sign_up)
      end

      it "re-renders the 'edit' template" do
        newsletter_sign_up = NewsletterSignUp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NewsletterSignUp.any_instance.stub(:save).and_return(false)
        put :update, :id => newsletter_sign_up.id.to_s, :newsletter_sign_up => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested newsletter_sign_up" do
      newsletter_sign_up = NewsletterSignUp.create! valid_attributes
      expect {
        delete :destroy, :id => newsletter_sign_up.id.to_s
      }.to change(NewsletterSignUp, :count).by(-1)
    end

    it "redirects to the newsletter_sign_ups list" do
      newsletter_sign_up = NewsletterSignUp.create! valid_attributes
      delete :destroy, :id => newsletter_sign_up.id.to_s
      response.should redirect_to(newsletter_sign_ups_url)
    end
  end

end
